name: Automatic Merge

on:
  push:
    branches:
      - main
  check_suite:
    types: [completed]

jobs:
  merge:
    runs-on: ubuntu-latest

    if: github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Merge pull request
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git fetch origin +refs/pull/${{ github.event.check_suite.pull_requests[0].number }}/merge:refs/remotes/origin/pr/${{ github.event.check_suite.pull_requests[0].number }}/merge
        git merge --no-ff --no-edit origin/pr/${{ github.event.check_suite.pull_requests[0].number }}/merge
        git push origin main
