name: Pylint and Comment PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.*"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Check for Python files
      id: pylint-check
      run: |
        python_files=$(git ls-files '*.py')
        if [ ! -z "$python_files" ]; then
          echo "Python files found. Proceeding with pylint analysis."
          pylint $python_files
        else
          echo "No Python files found. Skipping pylint analysis."
          exit 0
        fi

    - name: Comment PR with Pylint report
      if: always()
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.issue;
          const body = 'Pylint analysis:\n```' + '${{ steps.pylint-check.outputs.stdout }}' + '```';
          github.issues.createComment({ owner, repo, issue_number: number, body });
